# Day 11: NumPy

- https://numpy.org/
- https://numpy.org/doc/stable/user/quickstart.html

In [1]:
import numpy as np

### Example Questions

Q1. Create a NumPy array from a Python list and perform basic operations like addition, multiplication, etc.

In [2]:
nums = [21, 4, 3, 7]
arr1 = np.array(nums)
print(f"NumPy array: {arr1}")
arr_add = arr1 + arr1
print(f"Addition: {arr_add}")
mult_arr = arr1 * arr1
print(f"Elementwise Multiplication: {mult_arr}")
mat_mult1 = arr1 @ arr1.transpose()
print(f"Matrix Multiplication 1: {mat_mult1}")
mat_mult2 = arr1.transpose() @ arr1
print(f"Matrix Multiplication 2: {mat_mult2}")
scal_mult = arr1 * 3
print(f"Scalar Multiplication: {scal_mult}")
sqr_arr = arr1 ** 2
print(f"Square: {sqr_arr}")

NumPy array: [21  4  3  7]
Addition: [42  8  6 14]
Elementwise Multiplication: [441  16   9  49]
Matrix Multiplication 1: 515
Matrix Multiplication 2: 515
Scalar Multiplication: [63 12  9 21]
Square: [441  16   9  49]


Q2. Generate a NumPy array of random numbers and calculate its mean, median and standard deviation.

In [3]:
rng = np.random.default_rng()
arr2 = rng.random((2, 3))
print(arr2)
arr_mean = arr2.mean()
print(f"Mean: {arr_mean}")
arr_median = np.median(arr2)
print(f"Median: {arr_median}")
arr_std = arr2.std()
print(f"Standard Deviation: {arr_std}")

[[0.14074402 0.93819785 0.14608333]
 [0.01614363 0.76263547 0.92841115]]
Mean: 0.4887025753183288
Median: 0.45435940040113837
Standard Deviation: 0.39416661592706465


Q3. Create a NumPy array and reshape it into a different shape.

In [4]:
arr3 = np.array([(3, 4, 5), (6, 7, 8)])
print(arr3)
print("After reshaping it:")
arr3 = arr3.reshape(3, 2)
print(arr3)

[[3 4 5]
 [6 7 8]]
After reshaping it:
[[3 4]
 [5 6]
 [7 8]]


### Practice Questions

1. Given a list of numbers, create a NumPy array and find the sum and product of its elements.

In [5]:
nums = [[11, 22, 33, 44], [1, 2, 3, 4], [5, 6, 7, 8]]
arr4 = np.array(nums)
print(arr4)
print(f"Sum of elements: {arr4.sum()}")
print(f"Product of elements: {arr4.prod()}")

[[11 22 33 44]
 [ 1  2  3  4]
 [ 5  6  7  8]]
Sum of elements: 146
Product of elements: 1282900992


2. Implement a program that generates a NumPy array with numbers from 0 to 9 and reshapes it into a $3x3$ matrix.

In [6]:
arr5 = np.arange(9)
print(arr5)
print("After reshaping it:")
arr5 = arr5.reshape(3, 3)
print(arr5)

[0 1 2 3 4 5 6 7 8]
After reshaping it:
[[0 1 2]
 [3 4 5]
 [6 7 8]]


3. Write a Python program that uses NumPy to find the mean, median, and standard deviation of a dataset.

In [7]:
print(f"Dataset:\n{arr5}")
print(f"Mean: {arr5.mean()}")
print(f"Median: {np.median(arr5)}")
print(f"Standard Deviation: {arr5.std()}")

Dataset:
[[0 1 2]
 [3 4 5]
 [6 7 8]]
Mean: 4.0
Median: 4.0
Standard Deviation: 2.581988897471611


4. Create a function that takes a list of numbers and returns the NumPy array sorted in ascending order.

In [8]:
def sort_list(nums):
    arr = np.array(nums)
    arr.sort(axis= 0)
    return arr

nums = [4, 6, 3, 5]
print(sort_list(nums))

[3 4 5 6]


5. Given a list of lists, create a 2D NumPy array and find the sum of elements in each row and column.

In [9]:
lis_nums = [[4, 5, 2], [6, 9, 1]]
arr6 = np.array(lis_nums)
print(arr6)
print(f"Sum along rows: {arr6.sum(axis= 1)}")
print(f"Sum along columns: {arr6.sum(axis= 0)}")

[[4 5 2]
 [6 9 1]]
Sum along rows: [11 16]
Sum along columns: [10 14  3]


6. Implement a program that generates a random NumPy array and finds the maximum and minimum values.

In [10]:
random_array = np.ndarray((3, 3), dtype= int)
print(f"Random Array:\n{random_array}")
max_value = random_array.max()
min_value = random_array.min()
print(f"Maximum Value: {max_value}")
print(f"Minimum Value: {min_value}")

Random Array:
[[1 0 2]
 [3 4 5]
 [6 7 8]]
Maximum Value: 8
Minimum Value: 0


7. Write a function that takes a NumPy array and returns a new array with all elements squared.

In [11]:
def arr_sqrd(arr):
    return arr ** 2

print(arr1)
print("After array is squared:")
print(arr_sqrd(arr1))

[21  4  3  7]
After array is squared:
[441  16   9  49]


8. Given a NumPy array, calculate the dot product of the array with itself.

In [12]:
print(f"Array before dot product:\n{arr1}")
print("Array after dot product:")
print(arr1.dot(arr1))
print("")
print("Array before dot product")
print(arr6)
print("Array after dot product 1:")
print(arr6.dot(arr6.transpose()))
print("Array after dot product 2:")
print((arr6.transpose()).dot(arr6))

Array before dot product:
[21  4  3  7]
Array after dot product:
515

Array before dot product
[[4 5 2]
 [6 9 1]]
Array after dot product 1:
[[ 45  71]
 [ 71 118]]
Array after dot product 2:
[[ 52  74  14]
 [ 74 106  19]
 [ 14  19   5]]


9. Create a program that uses NumPy to calculate the inverse of a $2x2$ matrix.

In [13]:
print(f"Before matrix inverse:\n{random_array}")
print("After matrix inverse:")
print(np.linalg.inv(random_array).round(3))

Before matrix inverse:
[[1 0 2]
 [3 4 5]
 [6 7 8]]
After matrix inverse:
[[ 0.333 -1.556  0.889]
 [-0.667  0.444 -0.111]
 [ 0.333  0.778 -0.444]]


10. Implement a function that takes a NumPy array and returns the transpose of the array.

In [14]:
def arr_trans(arr1):
    arr2 = arr1.transpose()
    return arr2

print(f"Before:\n{arr6}")
print(f"After:\n{arr_trans(arr6)}")

Before:
[[4 5 2]
 [6 9 1]]
After:
[[4 6]
 [5 9]
 [2 1]]
